# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            EV3RT
tagline:          'RTOS-based Platform for Mindstorms EV3'
description:      'Program EV3 with RTOS!'
url:              https://ev3rt-git.github.io
baseurl:          /

author:
  name:           'Yixiao Li'
  url:            https://github.com/YixiaoLi
  email:          liyixiao7@gmail.com

paginate:         5

# Custom vars
version:          Beta 6-2

github:
  repo:           https://github.com/ev3rt-git
